[misc]
# Levels: trace, debug, info, warn, error, silent
# loglevel="info"

[twitch]
channels=[""]
clientid=""
secret=""

[database]
host=""
database=""
user=""
password=""
# Optional, will default to 5432 if undefined
# port=""
