[misc]
# Levels: off, fatal, error, warn, info, debug, trace, all
# loglevel="info"

[twitch]
channels=[""]
clientid=""
secret=""

[database]
host=""
database=""
user=""
password=""
# Optional, will default to 5432 if undefined
# port=""
